name: dacbr_cnpj
description: Uma biblioteca para consulta de CNPJ para desenvolvedores Dart (Console, Web e Flutter).
version: 1.0.1
homepage: https://projetodacbr.com.br/
repository: https://github.com/projetodacbr/dacbr_cnpj
issue_tracker: https://github.com/projetodacbr/dacbr_cnpj/issues
author: Mateus Penha <mateuspenha@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0+1

dev_dependencies:
  test: ^1.0.0
