name: dacbr_cnpj
description: Uma biblioteca para consulta de CNPJ para desenvolvedores Dart (Console, Web e Flutter).
version: 1.0.0
homepage: https://projetodacbr.com.br/
repository: https://github.com/mateuspenha/dacbr_cnpj
issue_tracker: https://github.com/mateuspenha/dacbr_cnpj/issues
author: Mateus Penha <mateuspenha@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0+1
  xml2json: ^3.0.3

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0